/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.fsm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.fsm.ui.internal.FsmActivator;

public class FSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FsmActivator.getInstance().getInjector("org.xtext.example.fsm.FSM");
	}

}
